# Generated by Django 5.0.6 on 2026-07-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DIAGNOSTIC', 'Agent de diagnostic'), ('RECOMMANDATION', 'Agent de recommandation')], max_length=20, verbose_name="Type d'agent")),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Agent IA',
                'verbose_name_plural': 'Agents IA',
            },
        ),
        migrations.CreateModel(
            name='BaseConnaissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200, verbose_name='Source')),
                ('domaine', models.CharField(max_length=200, verbose_name='Domaine')),
            ],
            options={
                'verbose_name': 'Base de connaissance',
                'verbose_name_plural': 'Bases de connaissance',
            },
        ),
        migrations.CreateModel(
            name='ConversationIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name="Message de l'utilisateur")),
                ('reponse', models.TextField(verbose_name="Réponse de l'IA")),
                ('horodatage', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
            ],
            options={
                'verbose_name': 'Conversation IA',
                'verbose_name_plural': 'Conversations IA',
                'ordering': ['horodatage'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu (texte)')),
                ('categorie', models.CharField(blank=True, max_length=150, verbose_name='Catégorie')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='URL source')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
