# Generated by Django 5.0.6 on 2026-07-06 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationia',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_ia', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='document',
            name='base_connaissance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assistant.baseconnaissance', verbose_name='Base de connaissance'),
        ),
    ]
