# Generated by Django 5.0.6 on 2026-07-06 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('norme', models.CharField(max_length=100, verbose_name='Norme ISO')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('niveau_difficulte', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé')], default='DEBUTANT', max_length=20, verbose_name='Niveau de difficulté')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('chapitre_hls', models.CharField(blank=True, max_length=100, verbose_name='Clause HLS (ISO)')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='catalogue.cours', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Chapitre',
                'verbose_name_plural': 'Chapitres',
                'ordering': ['cours', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='SousChapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(blank=True, verbose_name='Contenu pédagogique')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_chapitres', to='catalogue.chapitre', verbose_name='Chapitre')),
            ],
            options={
                'verbose_name': 'Sous-chapitre',
                'verbose_name_plural': 'Sous-chapitres',
                'ordering': ['chapitre', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VIDEO', 'Vidéo'), ('PDF', 'Document PDF'), ('IMAGE', 'Image'), ('LIEN', 'Lien externe')], default='LIEN', max_length=10, verbose_name='Type de média')),
                ('url', models.URLField(max_length=500, verbose_name='URL de la ressource')),
                ('sous_chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='catalogue.souschapitre', verbose_name='Sous-chapitre')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
            },
        ),
    ]
