# Generated by Django 5.0.6 on 2026-07-06 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilcompetence',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profils_competence', to=settings.AUTH_USER_MODEL, verbose_name='Apprenant'),
        ),
        migrations.AddField(
            model_name='profilcompetence',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profils_competence', to='catalogue.cours', verbose_name='Cours'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='catalogue.cours', verbose_name='Cours associé'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluations.quiz', verbose_name='Quiz'),
        ),
        migrations.AddField(
            model_name='reponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='evaluations.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='evaluations.quiz', verbose_name='Quiz'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterUniqueTogether(
            name='profilcompetence',
            unique_together={('apprenant', 'cours')},
        ),
    ]
