# Generated by Django 5.0.6 on 2026-07-06 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseDonnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_correcte', models.BooleanField(verbose_name='Réponse correcte ?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_donnees', to='evaluations.question', verbose_name='Question')),
                ('resultat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_donnees', to='evaluations.resultat', verbose_name='Résultat')),
            ],
            options={
                'verbose_name': 'Réponse donnée',
                'verbose_name_plural': 'Réponses données',
            },
        ),
    ]
