# Generated by Django 5.0.6 on 2026-07-07 13:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('evaluations', '0003_reponsedonnee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='apprenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_personnalises', to=settings.AUTH_USER_MODEL, verbose_name='Apprenant destinataire (quiz généré)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='chapitre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='catalogue.chapitre', verbose_name='Chapitre (quiz final)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='sous_chapitre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='catalogue.souschapitre', verbose_name='Sous-partie (micro-quiz)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='type_quiz',
            field=models.CharField(choices=[('MICRO', 'Micro-quiz de sous-partie (10 questions)'), ('FINAL', 'Quiz final de chapitre (50 questions)'), ('DECOUVERTE', 'Quiz de découverte (visiteurs)')], default='MICRO', max_length=12, verbose_name='Type de quiz'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='nb_correctes',
            field=models.PositiveIntegerField(default=0, verbose_name='Bonnes réponses'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='nb_questions',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de questions'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='type_resultat',
            field=models.CharField(choices=[('MICRO', 'Micro-quiz de sous-partie (10 questions)'), ('FINAL', 'Quiz final de chapitre (50 questions)'), ('DECOUVERTE', 'Quiz de découverte (visiteurs)')], default='MICRO', max_length=12, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='HistoriqueQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enonce', models.TextField(blank=True, verbose_name='Énoncé posé')),
                ('date_posee', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_questions', to=settings.AUTH_USER_MODEL, verbose_name='Apprenant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='evaluations.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Historique de question',
                'verbose_name_plural': 'Historique des questions',
            },
        ),
        migrations.CreateModel(
            name='ProgressionChapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('VERROUILLE', 'Verrouillé'), ('EN_COURS', 'En cours'), ('VALIDE', 'Validé')], default='VERROUILLE', max_length=12, verbose_name='Statut')),
                ('nb_tentatives', models.PositiveIntegerField(default=0, verbose_name='Tentatives quiz final')),
                ('meilleur_score', models.FloatField(default=0.0, verbose_name='Meilleur score (%)')),
                ('derniere_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_chapitres', to=settings.AUTH_USER_MODEL, verbose_name='Apprenant')),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='catalogue.chapitre', verbose_name='Chapitre')),
            ],
            options={
                'verbose_name': 'Progression (chapitre)',
                'verbose_name_plural': 'Progressions (chapitres)',
                'unique_together': {('apprenant', 'chapitre')},
            },
        ),
        migrations.CreateModel(
            name='ProgressionSousPartie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('VERROUILLE', 'Verrouillé'), ('EN_COURS', 'En cours'), ('VALIDE', 'Validé')], default='VERROUILLE', max_length=12, verbose_name='Statut')),
                ('lu', models.BooleanField(default=False, verbose_name='Contenu lu')),
                ('nb_tentatives', models.PositiveIntegerField(default=0, verbose_name='Nombre de tentatives')),
                ('meilleur_score', models.FloatField(default=0.0, verbose_name='Meilleur score (%)')),
                ('niveau_maitrise', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Niveau de maîtrise (0 à 1)')),
                ('contenu_simplifie', models.TextField(blank=True, verbose_name='Contenu simplifié (IA)')),
                ('derniere_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_sous_parties', to=settings.AUTH_USER_MODEL, verbose_name='Apprenant')),
                ('sous_chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='catalogue.souschapitre', verbose_name='Sous-partie')),
            ],
            options={
                'verbose_name': 'Progression (sous-partie)',
                'verbose_name_plural': 'Progressions (sous-parties)',
                'unique_together': {('apprenant', 'sous_chapitre')},
            },
        ),
    ]
