# Generated by Django 5.0.6 on 2026-07-07 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_quiz_apprenant_quiz_chapitre_quiz_date_creation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='nom_visiteur',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom du visiteur'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='prenom_visiteur',
            field=models.CharField(blank=True, max_length=150, verbose_name='Prénom du visiteur'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
